### ISSUE TITLE
Fresh install standalone version dosent work

### ISSUE THREAD

**Issue by HunterZeroSix** [didiatworkz/screenly-ose-monitor#11]
Hi
I setup up a fresh debian 9 and install your script
but i got a blank page
i think a webserver is needed, to get them work

Best regards
HunterZeroSix

**Comment by didiatworkz** [comment]
Hello @HunterZeroSix,
currently the standalone installation tested and work only with raspbian buster (I know.. It's a Debian port..)
The script install a nginx-light server (https://github.com/didiatworkz/screenly-ose-monitor/blob/master/assets/tools/ansible/roles/monitoring/tasks/main.yml#L66)
Can you attach the /var/log/nginx/error.log here?
Do the install process show any errors? - Can you attach them, too?

Best,
didiatworkz

**Comment by anakuron** [comment]
I also tried this out with fresh Debian 9 (used up to date AWS EC2 image)
so far the problems I've found are:
the installation script expects you to run it as user pi, if you don't it will say it's done but won't actually install everything.

so I created the user pi and run the script

Nginx is installed but the configuration file is directly in sites-enabled instead of sites-available and then a symlink in sites-enabled
I guess this works, but maybe not the best practice so I changed it anyway

Nginx monitor configuration expects PHP 7.3 socket but only php7.0 is installed by the script
so I upgraded to PHP 7.3 and checked out that Nginx can run the PHP with test file
` <?php phpinfo(); ?> ` 

which it does run,
but it won't run the index.php
getting error 500 from browser

that's as far as I got

**Comment by didiatworkz** [comment]
Hello together,
I changed the php packages to the version 7.3
-> Can you try this again. please?

**Comment by didiatworkz** [comment]
So now...
I check now the installed PHP Version and hope that problem is fixed now.
https://github.com/didiatworkz/screenly-ose-monitor/blob/master/assets/tools/ansible/roles/monitoring/tasks/main.yml#L72
The version number will be include into the monitoring.conf file
--> Can you check if everything is running now?

Thanks @anakuron for the info

Best 
didiatworkz

**Comment by anakuron** [comment]
yeah that works, I did a fresh install from a snapshot

**to reproduce:**
`sudo adduser pi`
create the user and user directory

`sudo adduser pi sudo`
adds user to sudo group so it can do the install

`su pi`
change to correct user

`bash <(curl -sL https://raw.githubusercontent.com/didiatworkz/screenly-ose-monitor/master/assets/tools/install_monitor.sh)`
wait it to install

`sudo systemctl restart nginx`
restart nginx

**Comment by didiatworkz** [comment]
Hello @anakuron 
thanks for your feedback - I will wait for @HunterZeroSix  response and then we can close this Issue.
Btw: Do you need really a restart of the nginx service?
Normally the installation do this: [Link](https://github.com/didiatworkz/screenly-ose-monitor/blob/master/assets/tools/ansible/roles/monitoring/tasks/main.yml#L90)
But when it work now I'm very happy :D 
Best

**Comment by HunterZeroSix** [comment]
Hey @didiatworkz and @anakuron 
Thanks for fixing the bug

Yes you have to restart the service
After that, everything works fine

Best regards
